trigger: none

pr:
- master

pool:
  vmImage: 'Ubuntu-18.04'

resources:
  repositories:
  - repository: templates
    type: github
    name: swellaby/azure-pipelines-templates
    endpoint: swellaby

steps:
- checkout: self
  path: app
- checkout: github://swellaby/azp-bump-tests
  path: 'functional-tests'

- script: npm pack
  displayName: 'npm pack'
  workingDirectory: $(Build.SourcesDirectory)/app

- script: |
    export PACKAGE_VERSION=$(node -e "console.log(require('./package.json').version);")
    echo "##vso[task.setvariable variable=packageVersion]$PACKAGE_VERSION"
  displayName: 'Extract package version'
  workingDirectory: $(Build.SourcesDirectory)/app

- task: Npm@1
  inputs:
    command: custom
    customCommand: 'run target:install -- $(Build.SourcesDirectory)/functional-tests/azp-bump-$(packageVersion).tgz'
    workingDir: $(Build.SourcesDirectory)/functional-tests
  displayName: 'Install app'

